@startuml

hide stereotype

skinparam rectangle {
  BackgroundColor White
  BorderColor Black
}

skinparam rectangle<<faded>> {
  BackgroundColor White
  BorderColor DarkGray
  FontColor DarkGray
}


frame "APIs" {

    rectangle "STAC"
    rectangle "Records API" <<faded>>
    rectangle "OGC Processes"
    rectangle "OpenID Connect"


    rectangle "S3\n(data access)"
    rectangle "HTTPS\n(data access)"
    rectangle "Commercial Data\nOrdering"
    rectangle "Mapping\nWM(T)S XYZ"
  }


@enduml
